apiVersion : v2
name: rabbitmq
description: A Helm chart for Kubernetes-based deployment of the rabbitmq component of the roboshop application
type: application
version: 1.0.0 # chart version
appVersion: 1.0.0 # version of the application being deployed