component :
  name : rabbitmq
  environment: dev
  namespace: roboshop
  replicas: 1

image:
  repository: "854481201869.dkr.ecr.us-east-1.amazonaws.com/stackly/rabbitmq"
  tag: "1.0.0"

endpoints:
  RABBITMQ_DEFAULT_USER: "roboshop"
  RABBITMQ_DEFAULT_PASS: "roboshop123"
  
###### PORTS #######
ports :
  containerPort: 5672
  servicePort: 5672


### Resource limits and requests for the catalogue component#####
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

  
   