component :
  name : redis
  environment: dev
  namespace: roboshop
  replicas: 1

image:
  repository: "854481201869.dkr.ecr.us-east-1.amazonaws.com/stackly/redis"
  tag: "1.0.0"

endpoints:

  ###### PORTS #######
ports :
  containerPort: 27017
  servicePort: 27017 



### Resource limits and requests for the catalogue component#####
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi


   