component :
  name : redis
  environment: dev
  namespace: roboshop
  replicas: 1

image:
  repository: redis
  tag: "6.2-alpine"

endpoints:

  ###### PORTS #######
ports :
  containerPort: 27017
  servicePort: 27017 



### Resource limits and requests for the catalogue component#####
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi


   