apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.component.name }}-secret
  namespace: {{ .Values.component.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.endpoints.MYSQL_ROOT_PASSWORD | quote }}
