apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.component.name }}-secret
  namespace: {{ .Values.component.namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.endpoints.RABBITMQ_DEFAULT_USER | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.endpoints.RABBITMQ_DEFAULT_PASS | quote }}
  
